# Generated by Django 3.2.9 on 2021-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
