# Generated by Django 3.2.9 on 2021-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_moduletask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletask',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
